### ISSUE TITLE
I parsed jquery w/ it and only found 6 regexps :(

### ISSUE THREAD

**Issue by sauerman** [polygonplanet/Chiffon#4]

**Comment by polygonplanet** [comment]
I found 71 regexps in jQuery v1.11.3 (Chiffon v1.4.0)
And, I have test whether the Chiffon and Esprima is the same result.
https://github.com/polygonplanet/Chiffon/blob/1.4.0/tests/test.js#L42-L44
Please tell me your execution environment or jQuery's version etc..
